[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies.scaffolding]
path = "../../scaffolding"
features = ["multi"]

[dependencies.scaffolding-ui]
path = "../../plugins/scaffolding-ui"
