[package]
name = "scaffolding"
version = "0.1.0"
edition = "2021"

[features]
default = ["multi"]
std = []
debugger = []
os-allocator = []
multi = ["std"]

[target.'cfg(target_family="unix")'.dependencies]
libc = "0.2.155"
